env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

language:
  node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

install:
  - npm install
  - npm install -g codecov

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mkdir ./images
  - cp ./places.js.sample places.js
  - cp ./.env.sample .env
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT