language:
  node_js

node_js:
  - "8"

install:
  - npm install
  - npm install -g codecov

script:
  - mkdir ./images
  - cp ./places.js.sample places.js
  - cp ./.env.sample .env
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov